const LIGHT_GREEN = '#03C988';
const DARK_BLUE = '#163172';
const CREAM = '#FFF6EA';
const LIGHT_BLUE = '#54A7FF';
const GREY = '#D0D0D0';
const DARK_GREY='#A9A9A9'
const BLACK = '#282828';
const RED = '#F34E4E';
const DARK_YELLOW = '#FFCC00';
const WHITE = '#FFFFFF';

export const COLORS = {
  PRIMARY: DARK_BLUE,
  SEONDARY: CREAM,
  ACTION: LIGHT_BLUE,
  ERROR: RED,
  WARNING: DARK_YELLOW,
  GREY: GREY,
  BLACK: BLACK,
  WHITE: WHITE,
  SUCCESS: LIGHT_GREEN,
  DARK_GREY:DARK_GREY
};
